{% set version = "1.2.4" %}

package:
    name: netcdf4
    version: {{ version }}

source:
    fn: netCDF4-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/n/netCDF4/netCDF4-{{ version }}.tar.gz
    md5: fb8083a17644bd559887b026fddd18a8

build:
    number: 2
    entry_points:
        - ncinfo = netCDF4.utils:ncinfo
        - nc4tonc3 = netCDF4.utils:nc4tonc3
        - nc3tonc4 = netCDF4.utils:nc3tonc4

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - cython
        - hdf5 1.8.17|1.8.17.*
        - libnetcdf 4.4.*
    run:
        - python
        - setuptools
        - numpy x.x
        - hdf5 1.8.17|1.8.17.*
        - libnetcdf 4.4.*

test:
    imports:
        - netCDF4
        - netcdftime
    commands:
        - ncinfo -h
        - nc4tonc3 -h
        - nc3tonc4 -h

about:
    home: http://github.com/Unidata/netcdf4-python
    license: OSI Approved
    summary: Provides an object-oriented python interface to the netCDF version 4 library.

extra:
    recipe-maintainers:
        - ocefpaf
        - pelson
